import {LevelManager,type ManageLevel} from './level-manager';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import type {Board} from '@/lib/tennis';
import {Loader2,Plus} from 'lucide-react';
export function BracketSetup({board,names,name,onName,size,onSize,format,onFormat,busy,revision,onManage,onSubmit}:{board:Board;names:string[];name:string;onName:(name:string)=>void;size:number;onSize:(size:number)=>void;format:string;onFormat:(format:string)=>void;busy:boolean;revision:number;onManage:ManageLevel;onSubmit:(event:React.FormEvent<HTMLFormElement>)=>void}){
 const selected=board.levels.find(l=>l.name===name),hasData=selected?.matches.some(m=>m.configured||m.players.some(Boolean)||m.court||m.date||m.time||m.codeHash||m.currentCode||m.status!=='scheduled');
 return <><div className="stack-form"><label className="field-label" id="setup-level-label">Poziom rozgrywek</label><Select value={selected?.name||''} onValueChange={onName} disabled={busy}><SelectTrigger className="format-select" aria-labelledby="setup-level-label"><SelectValue/></SelectTrigger><SelectContent>{names.map(n=><SelectItem key={n} value={n}>{n}</SelectItem>)}</SelectContent></Select><LevelManager level={selected} busy={busy} revision={revision} onManage={onManage}/></div>
 {!selected?<p>Wybierz poziom lub dodaj nowy.</p>:hasData?<p className="bracket-setup-note">Drabinka zawiera już mecze. Uzupełniaj je przez „Edytuj mecz” bezpośrednio w drabince.</p>:<form className="stack-form" onSubmit={onSubmit}>
  <label className="field-label" id="setup-round-label">Rundy play-off</label><Select value={String(size)} onValueChange={v=>onSize(Number(v))} disabled={busy}><SelectTrigger className="format-select" aria-labelledby="setup-round-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="2">Finał</SelectItem><SelectItem value="4">Półfinał + finał</SelectItem><SelectItem value="8">Ćwierćfinał + półfinał + finał</SelectItem><SelectItem value="16">1/8 + ćwierćfinał + półfinał + finał</SelectItem></SelectContent></Select>
  <p className="bracket-setup-note">Powstanie pusta drabinka dla {size} zawodników lub par.{size>2?' Zawiera także mecz o 3. miejsce.':''} Kliknij mecz w drabince, aby uzupełnić zawodników i termin.</p>
  <label className="field-label" id="setup-format-label">Format meczu</label><Select value={format} onValueChange={onFormat} disabled={busy}><SelectTrigger className="format-select" aria-labelledby="setup-format-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="super">2 sety + super tie-break do 10</SelectItem><SelectItem value="classic">Do 2 wygranych pełnych setów</SelectItem></SelectContent></Select>
  <button className="button dark full" disabled={busy}>{busy?<Loader2 className="spin" size={18}/>:<Plus size={18}/>} Utwórz pustą drabinkę</button>
 </form>}</>;
}
