'use client';
import {useEffect,useState} from 'react';
import {FileText,Plus,ExternalLink,Loader2,Trash2} from 'lucide-react';
import {toast} from 'sonner';
type Notice={id:string;title:string;description:string;uploadedAt:string;size:number};
type NoticeData={version:string;items:Notice[];error?:string};
export function Announcements({admin}:{admin:boolean}){
 const [data,setData]=useState<NoticeData|null>(null),[error,setError]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;const controller=new AbortController();async function load(){try{const r=await fetch('/api/announcements',{cache:'no-store',signal:controller.signal});const d=await r.json() as NoticeData;if(!r.ok)throw Error(d.error);if(active){setData(d);setError('');}}catch(e){if(active&&!controller.signal.aborted)setError((e as Error).message);}}void load();const timer=setInterval(()=>void load(),30000);return()=>{active=false;controller.abort();clearInterval(timer);};},[]);
 async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!data||busy)return;const form=event.currentTarget,body=new FormData(form),file=body.get('file');if(!(file instanceof File)||file.size>10*1024*1024){setError('Wybierz PDF o rozmiarze do 10 MB.');return;}setBusy(true);setError('');
  try{const r=await fetch('/api/announcements',{method:'POST',headers:{'X-Announcements-Version':data.version},body});const d=await r.json() as NoticeData;if(!r.ok){if(r.status===409){const fresh=await fetch('/api/announcements',{cache:'no-store'});if(fresh.ok)setData(await fresh.json() as NoticeData);}throw Error(d.error);}setData(d);form.reset();setOpen(false);toast.success('Dodano komunikat.');}catch(e){setError((e as Error).message||'Nie udało się wysłać pliku. Spróbuj ponownie.');}finally{setBusy(false);}}
 async function remove(n:Notice){if(!data||busy||!window.confirm(`Usunąć komunikat „${n.title}” wraz z plikiem PDF?`))return;setBusy(true);setError('');
  try{const r=await fetch('/api/announcements?id='+encodeURIComponent(n.id),{method:'DELETE',headers:{'X-Announcements-Version':data.version}});const d=await r.json() as NoticeData;if(!r.ok){if(r.status===409){const fresh=await fetch('/api/announcements',{cache:'no-store'});if(fresh.ok)setData(await fresh.json() as NoticeData);}throw Error(d.error);}setData(d);toast.success('Usunięto komunikat.');}catch(e){setError((e as Error).message||'Nie udało się usunąć komunikatu.');}finally{setBusy(false);}}
 return <section className="announcements-view" aria-label="Komunikaty"><div className="results-top"><h2>Komunikaty</h2>{admin&&<button className="button dark" onClick={()=>setOpen(!open)} aria-expanded={open} disabled={busy}><Plus size={17}/> Dodaj komunikat</button>}</div>
 {admin&&open&&<form className="announcement-form stack-form" onSubmit={upload}><label>Tytuł komunikatu<input name="title" required maxLength={120} disabled={busy} placeholder="np. Regulamin finałów"/></label><div className="announcement-fields"><label>Plik PDF<input name="file" type="file" accept="application/pdf,.pdf" required disabled={busy}/><small>Maksymalnie 10 MB</small></label><label>Czego dotyczy dokument?<textarea name="description" maxLength={1000} rows={3} disabled={busy} placeholder="Krótki opis dla zawodników"/></label></div><div className="announcement-actions"><button className="button dark" disabled={busy||!data}>{busy?<Loader2 size={17} className="spin"/>:<Plus size={17}/>} Opublikuj komunikat</button><button className="button outline" type="button" disabled={busy} onClick={()=>setOpen(false)}>Anuluj</button></div></form>}
 {error&&<p className="error-message" role="alert">{error}</p>}
 {!data&&!error&&<p className="schedule-note">Wczytywanie komunikatów…</p>}
 {data?.items.length===0&&<p className="schedule-empty">Organizator nie dodał jeszcze komunikatów.</p>}
 {data?.items.map(n=><article className="announcement" key={n.id}><div className="announcement-pdf"><FileText size={26}/><span>PDF</span></div><div className="announcement-copy"><h3>{n.title}</h3>{n.description&&<p>{n.description}</p>}<time dateTime={n.uploadedAt}>Dodano {new Intl.DateTimeFormat('pl-PL',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Warsaw'}).format(new Date(n.uploadedAt))}</time>{admin&&<small> · {(n.size/1024/1024).toFixed(2)} MB</small>}</div><div className="announcement-actions"><a className="button outline" href={'/api/announcements?id='+encodeURIComponent(n.id)} target="_blank" rel="noopener noreferrer">Otwórz PDF <ExternalLink size={16}/></a>{admin&&<button className="button outline" disabled={busy} onClick={()=>void remove(n)} aria-label={'Usuń komunikat: '+n.title}><Trash2 size={16}/> Usuń</button>}</div></article>)}
 </section>;
}
