import {LevelManager,type ManageLevel} from './level-manager';
import {RefereeOption} from './referee';
import {COURTS} from '@/lib/courts';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {makeLevel,isDoubles,dateLabel,type Board} from '@/lib/tennis';
import {Loader2,Plus} from 'lucide-react';
function ScheduleFields({index,dates}:{index:number;dates:string[]}){return <div className="form-grid"><label>Numer kortu<Select name={'court'+index} required><SelectTrigger className="format-select" aria-label="Numer kortu"><SelectValue placeholder="Wybierz kort"/></SelectTrigger><SelectContent>{COURTS.map(c=><SelectItem key={c.id} value={c.id}>{c.label}</SelectItem>)}</SelectContent></Select></label><label>Data<Select name={'date'+index} required><SelectTrigger className="format-select" aria-label="Data meczu"><SelectValue placeholder="Wybierz datę"/></SelectTrigger><SelectContent>{dates.map(date=><SelectItem value={date} key={date}>{dateLabel(date)}</SelectItem>)}</SelectContent></Select></label><label>Godzina<input type="time" name={'time'+index} required/></label></div>}
export function BracketSetup({board,names,name,onName,size,onSize,format,onFormat,busy,revision,onManage,onSubmit}:{board:Board;names:string[];name:string;onName:(name:string)=>void;size:number;onSize:(size:number)=>void;format:string;onFormat:(format:string)=>void;busy:boolean;revision:number;onManage:ManageLevel;onSubmit:(event:React.FormEvent<HTMLFormElement>)=>void}){
 const selected=board.levels.find(l=>l.name===name),draft=makeLevel(name,size),doubles=isDoubles(selected||name),published=selected?.matches.some(m=>m.players.some(Boolean));
 return <><div className="stack-form">
  <div><label className="field-label" id="setup-level-label">Poziom rozgrywek</label><Select value={selected?.name||''} onValueChange={onName} disabled={busy}><SelectTrigger className="format-select" aria-labelledby="setup-level-label"><SelectValue/></SelectTrigger><SelectContent>{names.map(n=><SelectItem key={n} value={n}>{n}</SelectItem>)}</SelectContent></Select></div>
  <LevelManager level={selected} busy={busy} revision={revision} onManage={onManage}/>
 </div>
 {!selected?<p className="bracket-setup-note">Wybierz poziom lub dodaj nowy, aby ustawić pary.</p>:published?<p className="bracket-setup-note">Pary tego poziomu są już opublikowane. Możesz zmienić jego nazwę lub usunąć poziom powyżej. Pary i terminy poprawisz przez „Edytuj mecz” na tablicy wyników.</p>:<form className="stack-form" onSubmit={onSubmit}>
 {!board.finalsDates?.length&&<p className="bracket-setup-note">Przed opublikowaniem par ustaw daty finałów w panelu organizatora.</p>}
  <div><label className="field-label" id="setup-round-label">Faza pucharowa rozpoczyna się od</label><Select value={String(size)} onValueChange={v=>onSize(Number(v))} disabled={busy}><SelectTrigger className="format-select" aria-labelledby="setup-round-label"><SelectValue/></SelectTrigger><SelectContent>{[16,8,4].map(n=><SelectItem key={n} value={String(n)}>{n===16?'1/8 finału':n===8?'Ćwierćfinałów':'Półfinałów'} — {n} {doubles?(n===4?'pary':'par'):'zawodników'}</SelectItem>)}</SelectContent></Select></div>
  <p className="bracket-setup-note">{size} {doubles?(size===4?'pary':'par'):'zawodników'} · {size} {size===4?'mecze':'meczów'}, w tym mecz o 3. miejsce. Zwycięzcy przechodzą do kolejnych rund automatycznie.</p>
  <div><label className="field-label" id="setup-format-label">Format meczu</label><Select value={format} onValueChange={onFormat} disabled={busy}><SelectTrigger className="format-select" aria-labelledby="setup-format-label"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="super">2 sety + super tie-break do 10</SelectItem><SelectItem value="classic">Do 2 wygranych pełnych setów</SelectItem></SelectContent></Select></div>
  <div key={selected.id+':'+size} className="bracket-setup-matches">{draft.matches.map((m,i)=><fieldset key={m.id}><legend>{m.stage}</legend>{!m.sources&&<div className="pair-inputs">{[0,1].map(j=><label key={j}>{doubles?'Para':'Zawodnik'} {j+1}<input name={'player'+(i*2+j)} placeholder={doubles?'Imię Nazwisko / Imię Nazwisko':'Imię i nazwisko'} maxLength={doubles?150:70} required disabled={busy}/></label>)}</div>}{m.sources&&<p className="bracket-pending-note">{m.stage==='O 3. miejsce'?'Przegrani półfinałów':`Zwycięzcy poprzedniej rundy`}</p>}<ScheduleFields index={i} dates={board.finalsDates||[]}/><RefereeOption index={i} busy={busy}/></fieldset>)}</div>
  <button className="button dark full" disabled={busy||!board.finalsDates?.length}>{busy?<Loader2 className="spin" size={18}/>:<Plus size={18}/>} Opublikuj pary i wygeneruj kody</button>
 </form>}</>;
}
